### ISSUE TITLE
BlenderVR installer (Windows 64-bit): old references to blender-vr

### ISSUE THREAD

**Issue by eugenschindler** [BlenderVR/source#34]
I installed BlenderVR using the Windows 64-bit install.exe and it didn't work, because there are two references in BlenderVR.bat and in BlenderVR-install.bat that point to blender-vr, while they should point to source.
For BlenderVR.bat:
 .\venv\\Scripts\python.exe .\blender-vr\blenderVR
should be
.\venv\\Scripts\python.exe .\source\blenderVR

and for BlenderVR-install.bat:
 %BVR_PATH%\venv\Scripts\pip3 install -r %BVR_PATH%\blender-vr\requirements.txt
should be
 %BVR_PATH%\venv\Scripts\pip3 install -r %BVR_PATH%\source\requirements.txt

I would like to give you a pull request, but cannot find the installer source code that creates these bat-files.

**Comment by dfelinto** [comment]
Thanks for the report.

@lpointal we changed the repository that we use for the source code. Could you please update the .bat files (bonus if you can push the repository with the files to BlenderVR github).

Meanwhile I will update blender-vr to be a 1:1 copy of source, to prevent people from noticing this issue.

(cc: @PyrApple )

**Comment by PyrApple** [comment]
I'll update .bat and create a .exe maker repo asa Martins finished/validated nothing else went astray during his BlenderVR windows install

**Comment by dfelinto** [comment]
Martins managed to install (after the .bat changes)

**Comment by eugenschindler** [comment]
Thanks a lot for fixing this issue so quickly! Kudos.
